# Generated by Django 3.0.8 on 2020-08-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('old_price', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'price',
            },
        ),
    ]
