# Generated by Django 3.0.8 on 2020-08-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200806_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isFirstUser',
            field=models.BooleanField(default=True),
        ),
    ]
