# Generated by Django 3.0.8 on 2020-07-20 18:14

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('scanImage', versatileimagefield.fields.VersatileImageField(null=True, upload_to='scan/', verbose_name='Image')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='ScanDetailsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', versatileimagefield.fields.VersatileImageField(null=True, upload_to='scan/', verbose_name='Image')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.ScanTable')),
            ],
        ),
    ]
