# Generated by Django 3.0.8 on 2020-08-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scandetailstable',
            name='scanDetailImageRaw',
            field=models.ImageField(blank=True, null=True, upload_to='scan/%Y/%m/%d'),
        ),
    ]
