# Generated by Django 3.0.8 on 2020-07-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_auto_20200720_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scantable',
            old_name='scanImage',
            new_name='scanImageRaw',
        ),
        migrations.AddField(
            model_name='scantable',
            name='scanImageUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
