# Generated by Django 3.0.8 on 2020-07-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0003_auto_20200721_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantable',
            name='scanImageRaw',
            field=models.ImageField(blank=True, null=True, upload_to='media/scan/'),
        ),
    ]
