# Generated by Django 3.0.8 on 2020-08-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hometype'),
        ),
    ]
