# Generated by Django 3.0.8 on 2020-07-20 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.IntegerField(choices=[(0, 'Blueprint'), (1, 'Themed 3D staging'), (2, 'Custom interio design 3D'), (3, 'Custom mobile home 3D')], default=0)),
                ('selected_theme', models.IntegerField()),
                ('tires', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'working'), (2, 'completed')], default=0)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('completed_date', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
