# Generated by Django 3.0.8 on 2020-08-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
