# Generated by Django 3.0.8 on 2020-07-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200720_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
