# Generated by Django 3.0.8 on 2020-08-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200721_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'ready'), (2, 'working'), (3, 'completed'), (4, 'cancelled'), (5, 'confirmed')], default=0),
        ),
    ]
