# Generated by Django 3.0.8 on 2020-08-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='expiry_date',
            field=models.CharField(max_length=255),
        ),
    ]
